[spaces-main.Repo]
url = "https://github.com/work-spaces/spaces"
rule-name = "spaces"
rev = "main"
clone = "Default"
help = "Checkout spaces from github.com/work-spaces/spaces"

[spaces-patch.Repo]
url = "https://github.com/work-spaces/spaces"
rev = "main"
new-branch = ["spaces"]
env = ["SPACES_INSTALL_ROOT=/Volumes/Code/workspace/.local"]
help = """
# spaces

## What is `spaces`?

- Reproducible workspace builder that manages
- Lightweight meta-build task-runner
- An awesome inner-loop shell

## Demo

- Checkout the `spaces` sources and dependencies including an isolated `rust` toolchain.
- Use the `spaces` task runner to build or use `spaces shell` to access dev tools directly in the workspace environment.

![spaces.run.shell](https://github.com/work-spaces/work-spaces.github.io/releases/download/assets-v0.2.0/spaces-demo.gif)

## Read the Docs

[Spaces Documentation](https://work-spaces.github.io/)

## Contribute

You can create a workspace dedicated to improving `spaces`.

```sh
spaces checkout-repo \
  --url=https://github.com/work-spaces/spaces \
  --rev=main \
  --new-branch=spaces \
  --name=issue-x-fix-something
cd issue-x-fix-something
spaces run //spaces:check
```

## Installing Spaces

`spaces` is a statically linked binary. Download it in the releases section.

Or install `spaces` at `$HOME/.local/bin`:

```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/work-spaces/install-spaces/refs/heads/main/install.sh)"
```

The command above requires `curl`, `unzip` and `sed`.

Or install from source using `cargo`:

```sh
git clone https://github.com/work-spaces/spaces
cd spaces
cargo install --path=crates/spaces --root=$HOME/.local --profile=release
```

Use `spaces` in github actions with https://github.com/work-spaces/install-spaces.

## Uninstall Spaces

- Delete the binary: `rm $HOME/.local/bin/spaces`.
- Delete the store: `rm -rf $HOME/.spaces`
"""

[spaces-dev.RepoDerived]
derive-from = "spaces-patch"
rev = "feature/v0.19"

[spaces-patch-default-install.RepoDerived]
derive-from = "spaces-dev"
env = ["SPACES_INSTALL_ROOT=/Volumes/Code/workspace/.local2"]

[devutils.Repo]
url = "https://github.com/work-spaces/devutils"
rev = "main"
new-branch = ["devutils"]

[testlab.Repo]
url = "https://github.com/work-spaces/spaces-e2e-testlab"
rev = "main"
new-branch = ["spaces-e2e-testlab"]
