[package]
name = "rule"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
anyhow-source-location.workspace = true
platform.workspace = true
printer.workspace = true
logger.workspace = true