name: Ubuntu MUSL Test Build

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build Ubuntu Binary (musl)
    runs-on: ubuntu-24.04

    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.3
        with:
          checkout: --locked --url=https://github.com/work-spaces/spaces --rev=${{ github.ref_name }}
          run: //spaces:install_release
