name: Ubuntu MUSL Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: work-spaces/spaces-checkout-run@v0.1.3
        with:
          checkout: --url=https://github.com/work-spaces/spaces --rev=${{ github.head_ref || github.ref_name }}
          run: //spaces:check_static_build
