name: Build and Publish Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing release tag to build and upload binaries for (e.g. v1.2.3)"
        required: true
        type: string

jobs:
  build-linux-x86_64:
    name: Build and Publish Linux x86_64
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.3
        with:
          checkout: >-
            --locked
            --url=https://github.com/work-spaces/spaces
            --rev=${{ inputs.tag }}
            --env=SPACES_RELEASE_TAG=${{ inputs.tag }}
            --env=GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          run: //spaces:publish_release

  build-linux-aarch64:
    name: Build and Publish Linux aarch64
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.3
        with:
          checkout: >-
            --locked
            --url=https://github.com/work-spaces/spaces
            --rev=${{ inputs.tag }}
            --env=SPACES_RELEASE_TAG=${{ inputs.tag }}
            --env=GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          run: //spaces:publish_release

  build-macos-aarch64:
    name: Build and Publish macOS aarch64
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.3
        with:
          checkout: >-
            --locked
            --url=https://github.com/work-spaces/spaces
            --rev=${{ inputs.tag }}
            --env=SPACES_RELEASE_TAG=${{ inputs.tag }}
            --env=GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          run: //spaces:publish_release

  build-windows-x86_64:
    name: Build and Publish Windows x86_64
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.3
        with:
          checkout: >-
            --locked
            --url=https://github.com/work-spaces/spaces
            --rev=${{ inputs.tag }}
            --env=SPACES_RELEASE_TAG=${{ inputs.tag }}
            --env=GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          run: //spaces:publish_release
